# Generated by Django 4.2.23 on 2025-08-27 20:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the track', max_length=255)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration of the track in sec', validators=[django.core.validators.MinValueValidator(20)])),
                ('album_order', models.PositiveIntegerField(help_text='Ordering in the album', validators=[django.core.validators.MinValueValidator(1)])),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='album.album')),
                ('artist', models.ManyToManyField(related_name='tracks', to='artist.artist')),
            ],
            options={
                'ordering': ['album', 'album_order'],
                'unique_together': {('album', 'album_order')},
            },
        ),
    ]
