# Generated by Django 4.2.23 on 2025-08-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='track',
            name='album_order',
        ),
    ]
