# Generated by Django 4.2.23 on 2025-08-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlisttracks',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='playlisttracks',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='playlist.PlaylistTracks', to='track.track'),
        ),
    ]
