# Generated by Django 4.2.23 on 2025-08-27 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_track_options_alter_track_unique_together_and_more'),
        ('playlist', '0002_remove_playlisttracks_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlisttracks',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playlisttracks',
            name='track_order',
            field=models.PositiveIntegerField(default=1, help_text='Ordering in the Playlist', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='playlisttracks',
            unique_together={('playlist', 'track', 'track_order')},
        ),
    ]
